### EXPLORATORY DATA ANALYSIS (EDA)

**STEP : 1** - Installing Required Libraries

Using pip command to install required libraries

In [1]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

**STEP : 2** - Importing Required Libraries

In [40]:
import pandas as pd   # importing pandas library

**STEP : 3** - Loading the Dataset

In [41]:
df = pd.read_csv("/content/drive/MyDrive/Applied_GenAI/tips.csv")  # Loading dataset in csv

In [4]:
df.head()   # Checking top 5 rows

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

**STEP : 4** - Understanding the Dataset

In [5]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [7]:
df.shape     # Checking the number of rows and columns

(244, 7)

In [8]:
df.columns   # Checking the list of columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [9]:
df.dtypes    # Checking datatypes of each column

total_bill    float64
tip           float64
sex            object
smoker         object
day            object
time           object
size            int64
dtype: object

The data contains float, int, object datatypes.

**STEP : 5** - Check for duplicates and Missing Data

In [10]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [11]:
df.duplicated()   # Checking the duplicated rows

0      False
1      False
2      False
3      False
4      False
       ...
239    False
240    False
241    False
242    False
243    False
Length: 244, dtype: bool

In [12]:
df[df.duplicated()]   # Display the duplicated rows in dataframe

     total_bill  tip     sex smoker   day   time  size
202        13.0  2.0  Female    Yes  Thur  Lunch     2

In [13]:
df = df.drop_duplicates()   # Drop the duplicate rows

In [15]:
df    # Final dataframe without any duplicates

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[243 rows x 7 columns]

In [16]:
df.isnull()    # Checking any null values in the dataset

     total_bill    tip    sex  smoker    day   time   size
0         False  False  False   False  False  False  False
1         False  False  False   False  False  False  False
2         False  False  False   False  False  False  False
3         False  False  False   False  False  False  False
4         False  False  False   False  False  False  False
..          ...    ...    ...     ...    ...    ...    ...
239       False  False  False   False  False  False  False
240       False  False  False   False  False  False  False
241       False  False  False   False  False  False  False
242       False  False  False   False  False  False  False
243       False  False  False   False  False  False  False

[243 rows x 7 columns]

In [17]:
df.isnull().sum()    # Finding the sum of null values in each column

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In our dataset, there are no null values.

**STEP : 7** - Statistical Summary of the Dataset

In [18]:
df.describe()   # Checking the statical summary of each numerical columns

       total_bill         tip        size
count  243.000000  243.000000  243.000000
mean    19.813868    3.002387    2.572016
std      8.910071    1.385002    0.952356
min      3.070000    1.000000    1.000000
25%     13.380000    2.000000    2.000000
50%     17.810000    2.920000    2.000000
75%     24.175000    3.575000    3.000000
max     50.810000   10.000000    6.000000

Here we can find the total count, mean, SD, min, max, 25th qtr, 50th and 75th qtr ranges in each numerical columns.

**STEP : 8** - Understanding Categorical Columns

In [19]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 243 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  243 non-null    float64
 1   tip         243 non-null    float64
 2   sex         243 non-null    object
 3   smoker      243 non-null    object
 4   day         243 non-null    object
 5   time        243 non-null    object
 6   size        243 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 15.2+ KB

Checking the info of each column with its datatype and non null values along with memory usage of the dataset.

In [21]:
df_cat = df[['sex','smoker','day','time']]   # Filter out the categorical columns alone.
df_cat.head()

      sex smoker  day    time
0  Female     No  Sun  Dinner
1    Male     No  Sun  Dinner
2    Male     No  Sun  Dinner
3    Male     No  Sun  Dinner
4  Female     No  Sun  Dinner

Checking the unique values of each categorical columns.

In [22]:
df_cat['sex'].unique()

array(['Female', 'Male'], dtype=object)

In [23]:
df_cat['smoker'].unique()

array(['No', 'Yes'], dtype=object)

In [24]:
df_cat['day'].unique()

array(['Sun', 'Sat', 'Thur', 'Fri'], dtype=object)

In [25]:
df_cat['time'].unique()

array(['Dinner', 'Lunch'], dtype=object)

Checking the total counts of each unique values in every columns.

In [26]:
df_cat['sex'].value_counts()

sex
Male      157
Female     86
Name: count, dtype: int64

Here male visitors are higher than female.

In [ ]:
df_cat['smoker'].value_counts()

smoker
No     151
Yes     92
Name: count, dtype: int64

Here non smoker visitors are more than smokers

In [27]:
df_cat['day'].value_counts()

day
Sat     87
Sun     76
Thur    61
Fri     19
Name: count, dtype: int64

Here in saturday has more visitors and friday has less visitors.

In [28]:
df_cat['time'].value_counts()

time
Dinner    176
Lunch      67
Name: count, dtype: int64

The visitors for dinner is higher than lunch.

**STEP : 8** - Outlier Detection

In [29]:
# Outlier detection on Total bill column

- lower bound = q1 - 1.5 x IQR

- upper bound = q3 + 1.5 x IQR

Here, q1 - 25th qtr,

q3- 75th qtr

IQR- Interquartile range.


***Outlier - The datapoints which are falling below q1 and falling above than q3.***

In [30]:
# Checking q1, q3 and IQR values for total column to findout the outliers

q1 = df['total_bill'].quantile(0.25)
q3 = df['total_bill'].quantile(0.75)
IQR = q3 - q1

Apply the values to findout lower bound and upper bound.

In [32]:
lower_bound = q1 - (1.5*IQR)
upper_bound = q3 + (1.5*IQR)

In [33]:
(df['total_bill'] < lower_bound) | (df['total_bill'] > upper_bound)

0      False
1      False
2      False
3      False
4      False
       ...
239    False
240    False
241    False
242    False
243    False
Name: total_bill, Length: 243, dtype: bool

In [35]:
df[(df['total_bill'] < lower_bound) | (df['total_bill'] > upper_bound)]   # below the lower bound or above the upper bound

     total_bill    tip     sex smoker   day    time  size
59        48.27   6.73    Male     No   Sat  Dinner     4
102       44.30   2.50  Female    Yes   Sat  Dinner     3
142       41.19   5.00    Male     No  Thur   Lunch     5
156       48.17   5.00    Male     No   Sun  Dinner     6
170       50.81  10.00    Male    Yes   Sat  Dinner     3
182       45.35   3.50    Male    Yes   Sun  Dinner     3
184       40.55   3.00    Male    Yes   Sun  Dinner     2
197       43.11   5.00  Female    Yes  Thur   Lunch     4
212       48.33   9.00    Male     No   Sat  Dinner     4

There are 9 datapoints are falling below and above the bounds which are called outliers. Handling outliers are important which affect the model performances.

In [37]:
df.describe()

       total_bill         tip        size
count  243.000000  243.000000  243.000000
mean    19.813868    3.002387    2.572016
std      8.910071    1.385002    0.952356
min      3.070000    1.000000    1.000000
25%     13.380000    2.000000    2.000000
50%     17.810000    2.920000    2.000000
75%     24.175000    3.575000    3.000000
max     50.810000   10.000000    6.000000

**STEP : 9** - Relationship Exploration using groupby

In [38]:
# Average tip by day

In [39]:
df.groupby('day')['tip'].mean()   # Using groupby function to findout the average tip in each day.

day
Fri     2.734737
Sat     2.993103
Sun     3.255132
Thur    2.784098
Name: tip, dtype: float64

During sundays the average tip values are high and lesser in friday.

In [ ]:
# Average Total bill by gender

df.groupby('sex')['total_bill'].mean()

sex
Female    18.115698
Male      20.744076
Name: total_bill, dtype: float64

Average total bill of male is higher than female.

These are all some basic exploratory data analysis including its shape, missing values, duplicate values, outlier detection, minimum, maximum, average values in each numberical columns of tips dataset.