**PANDAS**

- Pandas is a powerful, open source python library used for data manipulation and analysis.

INSTALLING PANDAS

We can use pip command to install pandas.

In [1]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

IMPORTING PANDAS

In [5]:
import pandas as pd

DATAFRAME OPERATIONS

- Creating DataFrame

Before we create a dictionary like data and convert that it into a DataFrame.

In [2]:
data = {
    'name': ['alice','bob','charlie'],
    'age' : [25,30,35],
    'city': ['delhi','mumbai','chennai']
}

In [3]:
data

{'name': ['alice', 'bob', 'charlie'],
 'age': [25, 30, 35],
 'city': ['delhi', 'mumbai', 'chennai']}

In [6]:
df = pd.DataFrame(data)
df

      name  age     city
0    alice   25    delhi
1      bob   30   mumbai
2  charlie   35  chennai

Here name, age and city are features and data are values.

- Saving the data as a csv file

Using to_csv to convert dataframe into a csv file.

In [7]:
df.to_csv("data.csv", index = False)   # If index=False means giving only actual values instead of index

- Read the data from csv

We can read_csv to convert into a DataFrame

In [8]:
df_1 = pd.read_csv("/content/data.csv")

In [9]:
df_1

      name  age     city
0    alice   25    delhi
1      bob   30   mumbai
2  charlie   35  chennai

UNDERSTANDING THE DATA

In [11]:
df_1.shape   # Checking the shape of the dataframe (Howmany rows and columns)

(3, 3)

In [12]:
df_1.columns  # Checking the columns list or features list

Index(['name', 'age', 'city'], dtype='object')

In [13]:
df_1.info()  # Checking the information about the dataframe.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   age     3 non-null      int64
 2   city    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

It is mainly used to check the null values and types of data like int, object and float etc.,

In [14]:
df_1.dtypes   # Alternate method to check datatypes.

name    object
age      int64
city    object
dtype: object

In [15]:
df_1.describe()  # It shows the statistical summary of the data.

        age
count   3.0
mean   30.0
std     5.0
min    25.0
25%    27.5
50%    30.0
75%    32.5
max    35.0

It will show the statistical summary only in the numberical columns.

- Accessing columns and rows

In [15]:
df_1

      name  age     city
0    alice   25    delhi
1      bob   30   mumbai
2  charlie   35  chennai

In [16]:
df_1['name']  # If we want to access any single column

0      alice
1        bob
2    charlie
Name: name, dtype: object

In [19]:
df_1.loc[0]   # It shows user defined index

name    alice
age        25
city    delhi
Name: 0, dtype: object

In [21]:
df_1.iloc[0]   # It shows predefined index location

name    alice
age        25
city    delhi
Name: 0, dtype: object

Difference between loc and iloc

In [23]:
new_data = {

    'Name': ['Ravi', 'Priya', 'Amit', 'Sara'],

    'Age': [25, 30, 22, 28],

    'City': ['Pune', 'Delhi', 'Mumbai', 'Chennai']

           }

In [24]:
new_data

{'Name': ['Ravi', 'Priya', 'Amit', 'Sara'],
 'Age': [25, 30, 22, 28],
 'City': ['Pune', 'Delhi', 'Mumbai', 'Chennai']}

In [25]:
df_2 = pd.DataFrame(new_data)

In [26]:
df_2

    Name  Age     City
0   Ravi   25     Pune
1  Priya   30    Delhi
2   Amit   22   Mumbai
3   Sara   28  Chennai

In [27]:
df_2 = pd.DataFrame(new_data, index = ['a','b','c','d'])
df_2

    Name  Age     City
a   Ravi   25     Pune
b  Priya   30    Delhi
c   Amit   22   Mumbai
d   Sara   28  Chennai

loc -- Access using user defined index.

In [28]:
df_2.loc['a']

Name    Ravi
Age       25
City    Pune
Name: a, dtype: object

iloc - Access using pre existing index

In [29]:
df_2.iloc[0]

Name    Ravi
Age       25
City    Pune
Name: a, dtype: object

FILTERING DATA

We can filter the data based on some condition.

*Example*


Records where age > 25

In [30]:
df_2   # Printing the dataframe

    Name  Age     City
a   Ravi   25     Pune
b  Priya   30    Delhi
c   Amit   22   Mumbai
d   Sara   28  Chennai

In [31]:
df_2['Age']   # Accessing age column

a    25
b    30
c    22
d    28
Name: Age, dtype: int64

In [32]:
df_2['Age']>25   # Filtering the data by condition

a    False
b     True
c    False
d     True
Name: Age, dtype: bool

It shows the boolean data, if filter out only by condition.

In [33]:
df_2

    Name  Age     City
a   Ravi   25     Pune
b  Priya   30    Delhi
c   Amit   22   Mumbai
d   Sara   28  Chennai

In [34]:
df_2[df_2['Age']>25]   # It shows the filtered data with the condition given.

    Name  Age     City
b  Priya   30    Delhi
d   Sara   28  Chennai

ADDING A COLUMN

In [33]:
df_2

    Name  Age     City
a   Ravi   25     Pune
b  Priya   30    Delhi
c   Amit   22   Mumbai
d   Sara   28  Chennai

In [36]:
df_2['salary'] = [50000,60000,70000,80000]    # Here 'salary' is a new column and the data are values.
df_2

    Name  Age     City  salary
a   Ravi   25     Pune   50000
b  Priya   30    Delhi   60000
c   Amit   22   Mumbai   70000
d   Sara   28  Chennai   80000

DELETE COLUMN

In [37]:
df_2['City']

a       Pune
b      Delhi
c     Mumbai
d    Chennai
Name: City, dtype: object

In [38]:
del df_2['City']   # Use 'del' function to delete a column

In [39]:
df_2

    Name  Age  salary
a   Ravi   25   50000
b  Priya   30   60000
c   Amit   22   70000
d   Sara   28   80000

ACTIVITY

**Real-Life Example: Student Data**

students = pd.DataFrame({

    "ID": [101, 102, 103],

    "Name": ["Anu", "Ravi", "Meena"],

    "Marks": [88, 76, 90]

Creating a dictionary

In [40]:
data_3 = {

"ID": [101, 102, 103],

"Name": ["Anu", "Ravi", "Meena"],

"Marks": [88, 76, 90]
}

Convert dictionary into a dataframe

In [41]:
students = pd.DataFrame(data_3)
students

    ID   Name  Marks
0  101    Anu     88
1  102   Ravi     76
2  103  Meena     90

Or we can directly create a dataframe directly.

In [43]:
students = pd.DataFrame({

"ID": [101, 102, 103],

"Name": ["Anu", "Ravi", "Meena"],

"Marks": [88, 76, 90]})

In [44]:
students

    ID   Name  Marks
0  101    Anu     88
1  102   Ravi     76
2  103  Meena     90

In [45]:
students.iloc[2]   # Accessing a row using index location

ID         103
Name     Meena
Marks       90
Name: 2, dtype: object

In [46]:
students['Name']   # Accessing a column

0      Anu
1     Ravi
2    Meena
Name: Name, dtype: object

In [47]:
students.iloc[1:]    # Slicing the particular rows and columns

    ID   Name  Marks
1  102   Ravi     76
2  103  Meena     90

In [48]:
students[['Marks','Name']]   # Printing two columns

   Marks   Name
0     88    Anu
1     76   Ravi
2     90  Meena

In [49]:
students.iloc[:,:]    # Alternate method to print entire dataframe. Where before the ',' is row and after ',' is column with start and stop.

    ID   Name  Marks
0  101    Anu     88
1  102   Ravi     76
2  103  Meena     90

In [50]:
students.iloc[1:,:]   # Printing entire values from second row

    ID   Name  Marks
1  102   Ravi     76
2  103  Meena     90

In [51]:
students.iloc[:,1:]   # Print entire values from second column

    Name  Marks
0    Anu     88
1   Ravi     76
2  Meena     90

Records where marks > 80

In [54]:
students

    ID   Name  Marks
0  101    Anu     88
1  102   Ravi     76
2  103  Meena     90

In [52]:
students[students['Marks'] > 80]  # Apply some condition to filter out the data

    ID   Name  Marks
0  101    Anu     88
2  103  Meena     90